# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bbabb567824ca8fb298bf98a7c9121fa"
application_url = "https://carter-displayed-there-converter.trycloudflare.com"
embedded = true
name = "my-new-awesome-app"
handle = "my-new-awesome-app-228"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "abc-dev-25.myshopify.com"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://carter-displayed-there-converter.trycloudflare.com/auth/callback",
  "https://carter-displayed-there-converter.trycloudflare.com/auth/shopify/callback",
  "https://carter-displayed-there-converter.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
